[package]
name    = "chainindex-node"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
chainindex-core    = { path = "../../crates/chainindex-core" }
chainindex-evm     = { path = "../../crates/chainindex-evm" }
chainindex-storage = { path = "../../crates/chainindex-storage", features = ["memory"] }

napi        = { version = "2", features = ["napi6", "async"] }
napi-derive = "2"
tokio       = { version = "1", features = ["full"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto       = true
strip     = "symbols"
opt-level = 3
