[package]
name    = "chainrpc-python"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name       = "chainrpc"
crate-type = ["cdylib"]

[dependencies]
chainrpc-core = { path = "../../crates/chainrpc-core" }
chainrpc-http = { path = "../../crates/chainrpc-http" }

pyo3          = { version = "0.21", features = ["extension-module"] }
pyo3-asyncio  = { version = "0.21", features = ["tokio-runtime"] }
tokio         = { version = "1", features = ["full"] }
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"

[profile.release]
lto       = true
strip     = "symbols"
opt-level = 3
