[package]
name    = "chaincodec-jni"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
name       = "chaincodec_jni"
crate-type = ["cdylib"]

[dependencies]
chaincodec-core     = { path = "../../../../crates/chaincodec-core" }
chaincodec-registry = { path = "../../../../crates/chaincodec-registry" }
chaincodec-evm      = { path = "../../../../crates/chaincodec-evm" }

jni        = { version = "0.21", features = ["invocation"] }
serde_json = "1"

[profile.release]
lto       = true
strip     = "symbols"
opt-level = 3
